--?? SCRIPT ORACLE 19C
--script_factorizacion.sql
CREATE TABLE FACTORIZACIONES (

    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    METODO VARCHAR2(100),
    EXPRESION VARCHAR2(200),
    RESULTADO VARCHAR2(300),
    FECHA_REGISTRO DATE DEFAULT SYSDATE,

    CONSTRAINT PK_FACTORIZACIONES
    PRIMARY KEY (ID)
);

COMMIT;

SELECT * FROM FACTORIZACIONES;